name: biblosphere
description: App to share books

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  geolocator: ^4.0.3

  stellar: ^0.3.2
  #firestore_helpers: ^3.1.0

  #geoflutterfire: ^2.0.3+5
  geoflutterfire:
      git: git://github.com/DarshanGowda0/GeoFlutterFire.git

  cloud_firestore: ^0.12.9+4

  firebase_storage: ^3.0.6

  firebase_auth: ^0.11.1+12

  permission_handler: ^3.0.1

  url_launcher: ^5.0.1

  cached_network_image: ^1.1.1

  fluttertoast: ^3.0.4

  intl: ^0.15.7

  image_picker: ^0.6.0+2

  share: ^0.5.3

  firebase_dynamic_links: ^0.4.0

  firebase_ml_vision: ^0.8.0

  firebase_messaging: ^5.0.1

  firebase_analytics: ^2.1.1+3

  photo_view: ^0.5.0

  flutter_crashlytics: ^0.2.0

  intro_views_flutter: ^2.3.0

  barcode_scan: ^1.0.0

  googleapis: ^0.53.0

  googleapis_auth: ^0.2.6

  firebase_ui: ^1.0.7

  flutter_launcher_icons: ^0.6.1

  shared_preferences: ^0.4.0

  in_app_purchase: ^0.2.1+4

  xml: ^3.3.1

  #Registration with Goodreads
  oauth1: ^1.0.4
# Run flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "images/biblosphere.png"
  android: true
  ios: true

dev_dependencies:
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Librarian50x50.jpg
    - images/shoot.png
    - images/surf.png
    - images/meet.png
    - images/home.png
    - images/local_library.png
    - images/message.png
    - images/bookmooch.jpg
    - images/bookcrossing.jpg
    - images/goodreads.png
    - images/librarything.png
    - images/amazon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AmaticSc
      fonts:
        - asset: fonts/AmaticSC-Regular.ttf
        - asset: fonts/AmaticSC-Bold.ttf
          weight: 700
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Bold.ttf
          weight: 700
    - family: MyIcons
      fonts:
        - asset: fonts/Flaticon.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
