name: biblosphere
description: App to share books
version: 1.3.0+1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  geolocator: ^5.1.4+2

  geoflutterfire: ^2.1.0

  cloud_firestore: ^0.13.5

  firebase_storage: ^3.1.5

  firebase_auth: ^0.16.0

  google_sign_in: ^4.0.14

  flutter_facebook_login: ^3.0.0

  flutter_signin_button: ^1.0.0

  permission_handler: ^4.4.0+hotfix.4

  url_launcher: ^5.2.2

  cached_network_image: ^2.0.0

  fluttertoast: ^4.0.1

  intl: ^0.16.0

  image_picker: ^0.6.3+4

  share: ^0.6.4

  firebase_dynamic_links: ^0.5.0+11

  #firebase_ml_vision: ^0.8.0

  firebase_messaging: ^6.0.13

  firebase_analytics: ^5.0.11

  firebase_crashlytics: ^0.1.3+3

  intro_views_flutter: ^2.8.1

  barcode_scan: ^2.0.2

  googleapis: ^0.53.0

  googleapis_auth: ^0.2.6

  flutter_launcher_icons: ^0.7.3

  shared_preferences: ^0.4.0

  purchases_flutter: ^1.1.0

  flushbar: ^1.10.2

  app_settings: ^4.0.0

  flutter_chips_input: ^1.8.3

  flutter_markdown: ^0.3.5

# Run flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "images/biblosphere.jpg"
  android: true
  ios: true

dev_dependencies:
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  cloud_firestore_mocks: ^0.4.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/biblosphere.jpg
    - images/Librarian50x50.jpg
    - images/shoot.png
    - images/surf.png
    - images/meet.png
    - images/home.png
    - images/local_library.png
    - images/message.png
    - images/bookmooch.jpg
    - images/bookcrossing.jpg
    - images/goodreads.png
    - images/librarything.png
    - images/amazon.png
    - images/icons/icons8-add-book-100.png
    - images/icons/icons8-books-100.png
    - images/icons/icons8-search-100.png
    - images/icons/icons8-communication-100.png
    - images/icons/icons8-wallet-100.png
    - images/icons/icons8-coins-100.png
    - images/icons/icons8-barcode-scanner-100.png
    - images/icons/icons8-shopping-cart-100.png
    - images/icons/icons8-online-support-100.png
    - images/icons/icons8-technical-support-100.png
    - images/icons/icons8-handshake-100.png
    - images/icons/icons8-exit-100.png
    - images/icons/icons8-settings-100.png
    - images/icons/icons8-cancel-100.png
    - images/icons/icons8-add-100.png
    - images/icons/icons8-return-100.png
    - images/icons/icons8-trash-100.png
    - images/icons/icons8-share-100.png
    - images/icons/icons8-bank-cards-100.png
    - images/icons/icons8-receive-cash-100.png
    - images/icons/icons8-unavailable-100.png
    - images/icons/icons8-sent-100.png
    - images/icons/icons8-filter-100.png
    - images/icons/icons8-clear-filters-100.png
    - images/icons/icons8-account-100.png
    - images/icons/icons8-paper-plane-100.png
    - images/icons/icons8-image-gallery-100.png
    - images/icons/icons8-compact-camera-100.png
    - images/icons/icons8-attach-90.png
    - images/icons/icons8-heart-100.png

    # dictionaries and lists
    - assets/languages.json

    # credentials for DialogFlow
    #- assets/dialogflow.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyIcons
      fonts:
       - asset: fonts/Flaticon.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
