name: biblosphere
description: App to share books

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  geolocator: ^5.1.4+2

  stellar: ^0.3.2
  #firestore_helpers: ^3.1.0

  #geoflutterfire: ^2.0.3+5
  geoflutterfire:
      git: git://github.com/DarshanGowda0/GeoFlutterFire.git

  cloud_firestore: ^0.12.9+5

  #firebase_storage: ^3.0.6

  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.14
  flutter_facebook_login: ^3.0.0
  flutter_signin_button: ^1.0.0

  #firebase_ui: 1.0.8

  #firebase_auth: ^0.11.1+12
  #firebase_ui: 1.0.7


  permission_handler: ^3.0.1

  url_launcher: ^5.2.2

  cached_network_image: ^2.0.0

  fluttertoast: ^3.1.3

  intl: ^0.16.0

  #image_picker: ^0.6.0+2

  share: ^0.5.3

  firebase_dynamic_links: ^0.5.0+1

  #firebase_ml_vision: ^0.8.0

  firebase_messaging: ^5.0.1

  firebase_analytics: ^5.0.2

  #photo_view: ^0.5.0

  flutter_crashlytics: ^0.2.0

  intro_views_flutter: ^2.3.0

  barcode_scan: ^1.0.0

  googleapis: ^0.53.0

  googleapis_auth: ^0.2.6

  flutter_launcher_icons: ^0.7.3

  shared_preferences: ^0.4.0

  in_app_purchase: ^0.2.2+2

  xml: ^3.3.1

  flutter_dialogflow: ^0.1.0

  #Registration with Goodreads
  oauth1: ^1.0.4

  flushbar: ^1.9.1

  app_settings: ^3.0.1

# Run flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "images/biblosphere.jpg"
  android: true
  ios: true

dev_dependencies:
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  mock_cloud_firestore:
    git: git://github.com/ozanturksever/mock_cloud_firestore.git

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/biblosphere.jpg
    - images/Librarian50x50.jpg
    - images/shoot.png
    - images/surf.png
    - images/meet.png
    - images/home.png
    - images/local_library.png
    - images/message.png
    - images/bookmooch.jpg
    - images/bookcrossing.jpg
    - images/goodreads.png
    - images/librarything.png
    - images/amazon.png
    - images/icons/icons8-add-book-100.png
    - images/icons/icons8-books-100.png
    - images/icons/icons8-search-100.png
    - images/icons/icons8-communication-100.png
    - images/icons/icons8-wallet-100.png
    - images/icons/icons8-coins-100.png
    - images/icons/icons8-barcode-scanner-100.png
    - images/icons/icons8-shopping-cart-100.png
    - images/icons/icons8-online-support-100.png
    - images/icons/icons8-technical-support-100.png
    - images/icons/icons8-handshake-100.png
    - images/icons/icons8-exit-100.png
    - images/icons/icons8-settings-100.png
    - images/icons/icons8-cancel-100.png
    - images/icons/icons8-add-100.png
    - images/icons/icons8-return-100.png
    - images/icons/icons8-trash-100.png
    - images/icons/icons8-share-100.png
    - images/icons/icons8-bank-cards-100.png
    - images/icons/icons8-receive-cash-100.png
    - images/icons/icons8-unavailable-100.png
    - images/icons/icons8-sent-100.png
    - images/icons/icons8-filter-100.png
    - images/icons/icons8-clear-filters-100.png
    - images/icons/icons8-account-100.png
    - images/icons/icons8-paper-plane-100.png

    # credentials for DialogFlow
    - assets/dialogflow.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyIcons
      fonts:
       - asset: fonts/Flaticon.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
